#import "@preview/mitex:0.2.4": *
#set heading(numbering: "1.1.1.")
#set math.equation(numbering: "(1)")
#set page(numbering: "1", number-align: right)
= Introduction
// Speaker and microphone are widely used in our daily life...  
= Theoretical Background
== Polarization
Electric field can polarized dielectric material. There are several polarization in the material, they are electronic polarization, ionic polarization, and orientation polarization. @ionic-polarization demonstrates the net polarization happens when exerting an external electric field, the postive charge and negative charge will flow to opposite direction of the field. With the polarization, the interal charge distribution will be disrupted, leading to the generation of the electrical field. The electric field can generate a voltage, and this voltage can produce a corresponding signal that enters the circuit. 

#figure(
  image("ionic-polarization.svg", width: 65%),
  caption: [
    The effect of an external electric field on an ionic material. 
  ],
)<ionic-polarization>

== Piezoelectric
=== Crystal strcture
Piezoelectric materials (PEM) are materials that can generate an net polarization internally in response to an applied mechanical stress. Without the applied stress, the material is in a neutral state. While the stress applied to the crystal of centro-symmetric materials, the unit cell becomes strained. However, the center of mass of the negative charge still concides with the positive charge so that results in a zero net polarization meaning this crystal strcture is not capable for the PEM. The PEM is always non-centro-symmetric. When stress applied, the center of the mass for the postive and negative charges will displace, result in a net polarization difference showed in @non-centro-crystal. // cite material physics lecture notes. 

#figure(
  image("non-centra-symmetry.png", width: 70%),
  caption: [
    a) The cystal stucture of non-centro-symmetric material. b) The net polarization when stress applied on vertical direction. c) The net polarization when stress applied on horizontal direction.
  ],
)<non-centro-crystal>

=== Piezoelectric effect
The pizeoelectricity can be understood as a linear electromechanical interaction between the mechanical and electrical states. The linearity could be written as @coefficient, 
$ P_i = d_(i j) T_j $<coefficient>
supposed the $T_j$ is the stress along $j$ direction and $P_i$ is the polarization along $i$ direction. The $d_(i j)$ is the piezoelectric coefficient. Air propagates from the top to the bottom, exerting pressure perpendicular to the PEM, which causes charge to be generated in the horizontal direction. 

The piezoelectric effect is reversible, meaning that the material can also deform when an electric field is applied. In this project, the microphone is based on the stress applied on the PEM, and the speaker is based on the electric field applied on the PEM. However, in this project, we focus on the microphone. 
// need to add more words in the future
== Almunium Nitride
//temporally skip the introduction of Almunium Nitride
== Figure of Merit
The figure of Merit (FOM) is a parameter that is used to evaluate the performance of the microphone. More charge is generate, the more sensitivity the microphone has. //take reference to one journal article.
Also the flatness of the electricity response given by the microphone is another important parameter, avoiding the potential distortion of the sound. For these sound frequency that has low response in the electrical field, the microphone will have a low sensitivity. To compensate for this, the external circuit should amplify these low-response frequency, leading to amplication of the noise. Therefore, the total harmonic distortion (THD) increases. //有待考究
=== Total stress on PEM<stress>
Since the pizeoelectricity is a linear relationship with the stress applied on the PEM, we can focus on the total stress that given by the sound wave. The total stress can be written as @total-stress,
#mitex(`
  $T_j = \iint_{\mathcal{S}} F_j \, dA$
`)<total-stress>
supposed $j$ is the direction of the stress, $F_j$ is the force applied on the PEM at every position, and $A$ is area of the PEM. The total stress is the integration of the force applied on the PEM. The more stress given by the sound wave, the more charge will be generated.
=== Total charge generated by PEM<charge>
To direct evaluate the performance, we can directly use total charge. The total charge generated can be written as @total-charge, 
#mitex(`
  $Q = \iint_{\mathcal{S}} \sigma \, dA$
`)<total-charge>
while the $sigma$ is the charge density on the PEM. The total charge is the integration of the charge density on PEM. 
=== Across over the frequency range
In this project, we only consider the frequency could be heard by human, which is from 20~Hz -- 20~kHz. The values from @stress and @charge need to be integral over the frequency range. The FOM can be written as @FOM or @FOM2, 
$ "FOM"=integral_(20)^(20000) Q_p d f $<FOM>
or 
$ "FOM"=integral_(20)^(20000) T_p d f $<FOM2>
where $p$ is the index of the frequency. 

== Genetic algorithm
//temporally skip the introduction of genetic algorithm

= Integration of the library of Pygad, Mph and COMSOL
// not finished yet, gonna to add it later
= 2D model 
// slowly write it
= 3D Model
== Simplication of the model
After convertting from 2D to 3D model, the computational requirements for simulating the model have significantly increased, leading to a corresponding increase in the time needed to obtain FOM. To reduce the computational requirements, the model has to be simplified. 
=== Symmetry
The membrane of my microphone is circular, making it easy to divide into two, four, or eight equal parts. The geometry design on each segment can be duplicated across the others, resulting in identical simulation outcomes for each section. With the decrease of area applied on mesh operation, the accuracy of the final result will increase for the same mesh granularity. 

However, the free geometry design is about destorying the symmetry of the model inherently. This method has contrain on cutting the membrane method. The number of the segments need to be considered accordingly. 
=== Mesh operation

=== Use stress as FOM


== Simulation Setup

